name: Rust

on:
  push:
    branches: [ "release/*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo test --verbose
  publishing:
    name: "Publising to crates.io"
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - name: Extra Cargo
        run: cargo install --path .
      - name: Build
        run: cargo build
      - name: Publish
        run: cargo caw-publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
