name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

jobs:
  test_and_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Extra Cargo
      run: cargo install cargo-is-version-published
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: cargo build --verbose
    - name: Publish
      run: if [[ "$(cargo is-version-published ./Cargo.toml)" = "no" ]]; then cargo publish; fi